---
title: "**Methods**"
date: "`r Sys.Date()`"
output: 
  html_document:
    self_contained: false
always_allow_html: true
---

## **What to expect**

This section is used to analyze the flood frequency and potential culvert sizing above the users selected point in the **Map** tab. This is accomplished by generating geospatial parameters through free and opensource softwares (FOSS) like USGS Stream Stats (Ries III et al., 2017) and R (Team, R, 2020). Furthermore, in field observations (bankfull- and active channel-width) can be added to the analysis as well. The parameters generated via USGS Stream Stats are many and depend on location, e.g. states, regions, etc. The geospatial parameters used by Omang, Parrett and Hull (1983) & Parrett and Johnson (2004) are mean annual precipitation, percentage of forest and drainage area, which are then used to calculate flood frequency using these parameters. In addition,  USGS Regional Regression Estimates (USGS RRE) will use the values and methods associated with specific location methods to generate peak flow estimates (Ries III et al., 2017), e.g. the **Peak Flow** tab will generate this. Moreover, if the user has in-field measurements then Omang, Parrett and Hull (1983) & Parrett and Johnson (2004) take into account bankfull width and active channel width to generate flood frequency estimates. Finally, calculations for culvert size are recommended using flood frequency estimations and methods from American Iron, & Steel Institute (1983).

## **References**

American Iron, & Steel Institute. (1983). Handbook of steel drainage & highway construction products. American Iron and Steel Institute.

Omang, R. J., Parrett, C., & Hull, J. A. (1986). Methods for estimating magnitude and frequency of floods in Montana based on data through 1983 (No. 86-4027). US Geological Survey.

Parrett, C., & Johnson, D. R. (2004). Methods for estimating flood frequency in Montana based on data through water year 1998 (Vol. 3, No. 4308). US Department of the Interior, US Geological Survey.

Ries III, K. G., Newson, J. K., Smith, M. J., Guthrie, J. D., Steeves, P. A., Haluska, T. L., ... & Vraga, H. W. (2017). StreamStats, version 4 (No. 2017-3046). US Geological Survey.

Team, R. (2020). RStudio: Integrated development for R. RStudio Inc.(2015). Acknowledgements This work was supported by Fundação para a Ciência e Tecnologia (FCT), Azores.